### ISSUE TITLE
let's remove most of Constants.jl and URL.jl

### ISSUE THREAD

**Issue by Krastanov** [krishna-praneet/QuantumSavoryServer#2]
These make the code more difficult to read. That level of abstraction does not seem necessary, especially for things like `EMPTY_STRING = ""`. Similarly about the URLs -- almost of of these are used in a single location -- it would be much easier to read the code if the actual URL is present, instead of a constant.

Generally I am leaning towards minimizing boilerplate and abstraction until something is repeated three times (two repetitions are not really worth spending the effort of abstracting away (a vague rule of thumb))

**Comment by krishna-praneet** [comment]
Got it! Thank you for the feedback, I will fix this in the upcoming PR.
